Change the whole concept of main and make it more readeble

diff --git a/wana b/wana
--- a/wana
+++ b/wana
@@ -1,68 +1,90 @@
 #!/bin/bash 
 
-# set variables
-first_arg=$1
-
 main() {
 
-    log-checker
+    command_name=""
+    filtr_name=""
+    file_name="${@: -1}"
 
-    if [ $# -gt 1 ]; then
-        # check the first argument and decide what to do
-        case $first_arg in 
-            "list-ip")
-            shift 1
-
-            list-ip "$@"
-            
-            ;;
-            "list-hosts") 
-            shift 1
-
-            list-hosts "$@"
-
-            ;;
-
-            "list-uri")
-            shift 1
-            
-            list-uri "$@"
-
-            ;;
-            "hist-ip")
-            shift 1
-
-            hist-ip "$@"
-
-            ;;
-            "hist-load")
-            shift 1 
-
-
-            ;;    
-        esac
-    fi
+    log-checker "$@" || return 1
     
+    # loop all arguments
+    while [ $# -gt 0 ]; do
+        # check the first argument and decide what to do
+        case $1 in 
+            "list-ip"|"list-hosts"|"list-uri"|"hist-ip"|"hist-load")
+            # if find one of the command save it and break loop
+            command_name="$1"
+            shift
+            break
+            ;;
+            *)
+
+            break 
+            ;;
+        esac
+    done
+
+    # condition if no commands or filter are written
+   if [[ $# -eq 0 ]]; then 
+
+        find . -name "*log*" -print | xargs -0 cat
+    
+    else
+    
+        if [[ "$file_name" == *.gz ]]; then
+            zcat "$@" | sort -u
+        else 
+            cat "$@" | sort -u
+    
+        fi
+    fi
+
+ 
+
 }
 
 log-checker() {
-
-    # Checks if the file contains something
-    if [[ ! -f "$@" ]]; then
-        echo "Error, log does not exist" ;
+    
+    # Checks if the file exist
+    if [[ ! -f "$file_name" ]]; then
+        echo "Error, $file_name does not exist" ;
         return 1 
     # Checks if the file is not empty
-    elif [[ ! -s "$@" ]]; then
-        echo "Error, $@ is empty";
+    elif [[ ! -s "$file_name" ]]; then
+        echo "Error, $file_name is empty";
         return 1 
     fi
     return 0
 }
 
+# apply command using saved command name
+command-apply() {
+
+    case "$command_name" in 
+        "list-ip")
+        
+        list-ip "$@"
+        ;;
+        "list-hosts")
+
+        list-hosts "$@"
+        ;;
+        "list-uri")
+
+        list-uri "$@"
+        ;;
+        "hist-ip")
+
+        hist-ip "$@"
+        ;;
+    esac
+}
+
 list-ip() {
     
     # Print list of the first column that contains IP addresses
-    awk '{print $1}' "$@"
+    awk '{print $1}' "$@" | sort -u
 }
 
 list-hosts() {
@@ -70,7 +92,7 @@ list-hosts() {
     # Make list of IP address that are piped into loop
     awk '{print $1}' "$@" | while read ip; do
     # For each IP address is made DNS lookup
-    host $ip | awk '{print $NF}'
+    host $ip | awk '{print $NF}' | sort -u
     done 
 
 }
@@ -78,7 +100,7 @@ list-hosts() {
 list-uri() {
     
     # filter all lines without HTTP/1.1 then prints list of uri-
-    grep "HTTP/1.1" "$@" | awk '{print $7}' 
+    grep "HTTP/1.1" "$@" | awk '{print $7}' | sort -u
 
 }
 
@@ -100,10 +122,10 @@ hist-ip() {
 
 }
 
-hist-load() {
+# hist-load() {
 
     # first need to do time filter
 
-}
+# }
 
 main "$@"
